language: node_js

jdk:
    - oraclejdk7

env:
    - NEO4J_VERSION="2.2.3"

before_install:
    # install Neo4j locally:
    - wget dist.neo4j.org/neo4j-community-$NEO4J_VERSION-unix.tar.gz
    - tar -xzf neo4j-community-$NEO4J_VERSION-unix.tar.gz
    - echo "dbms.security.auth_enabled=false" >> neo4j-community-$NEO4J_VERSION/conf/neo4j-server.properties
    - neo4j-community-$NEO4J_VERSION/bin/neo4j start

node_js:
  - "0.12"
matrix:
  fast_finish: true
  allow_failures:
    - node_js:
      - "0.11"
      - "0.11"
      - "0.10"
      - "iojs"
